roasters:
  rocket:
    name: rocket
    url: https://rocketcoffee.co.nz
  vanguard:
    name: vanguard
    url: https://vanguardcoffee.co.nz
  grey_coffee:
    name: grey_coffee
    url: https://greyroastingco.com/
  ozone:
    name: ozone
    url: https://ozonecoffee.co.nz
  wolf:
    name: wolf
    url: https://www.wolfcoffee.co.nz/

ai:
  provider: "azure"  # Future-proofing for other providers
  azure:
    # All sensitive values loaded from environment variables
    api_key: "${AZURE_OPENAI_API_KEY}"
    api_base: "${AZURE_OPENAI_ENDPOINT}"
    deployment_name: "${AZURE_OPENAI_DEPLOYMENT}"
    api_version: "${AZURE_OPENAI_API_VERSION}"
    temperature: 0.0  # Keep it deterministic for data extraction
    response_format: "json_object"  # Use structured output
  
  # Extraction settings
  max_retries: 3
  timeout_seconds: 30
  batch_size: 10  # Number of products to process in parallel

image_processing:
  target_height: 600  # Target height in pixels for downsampled images
  jpeg_quality: 85    # JPEG compression quality (0-100)
