"""Add blacklist fields to ProductExtendedDetails

Revision ID: 3c8a2e610918
Revises: 
Create Date: 2025-04-26 13:28:59.686802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8a2e610918'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if columns exist, if not add them
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('product_extended_details')]
    
    if 'is_blacklisted' not in columns:
        op.add_column('product_extended_details', sa.Column('is_blacklisted', sa.Boolean(), nullable=True, server_default=sa.text('0')))
    
    if 'blacklist_reason' not in columns:
        op.add_column('product_extended_details', sa.Column('blacklist_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the columns if they exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('product_extended_details')]
    
    if 'blacklist_reason' in columns:
        with op.batch_alter_table('product_extended_details') as batch_op:
            batch_op.drop_column('blacklist_reason')
    
    if 'is_blacklisted' in columns:
        with op.batch_alter_table('product_extended_details') as batch_op:
            batch_op.drop_column('is_blacklisted')
    # ### end Alembic commands ###
